---
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  simple-checks:
    uses: tuxpeople/containers/.github/workflows/simple-checks.yaml@main

  get-changed-images:
    uses: tuxpeople/containers/.github/workflows/get-changed-images.yaml@main

  build-images:
    needs: ["simple-checks", "get-changed-images"]
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    uses: tuxpeople/containers/.github/workflows/build-images.yaml@main
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
    with:
      appsToBuild: "${{ needs.get-changed-images.outputs.addedOrModifiedImages }}"
      pushImages: false
      sendNotifications: false
