---
name: Scheduled Release

permissions:
  contents: write
  packages: write

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appsToBuild:
        description: App(s) to build
        required: false
        type: string
        default: all
      force:
        description: Force rebuild
        type: boolean
        default: false
        required: true
  schedule:
    - cron: "0 * * * *"

jobs:
  simple-checks:
    name: Simple Checks
    uses: tuxpeople/containers/.github/workflows/simple-checks.yaml@main

  build-images:
    name: Build Images
    needs: simple-checks
    uses: tuxpeople/containers/.github/workflows/build-images.yaml@main
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
    with:
      appsToBuild: ${{ inputs.appsToBuild }}
      force: ${{ inputs.force == true }}
      pushImages: true
      sendNotifications: true

  render-readme:
    name: Render Readme
    needs: build-images
    uses: ./.github/workflows/render-readme.yaml
    secrets:
      BOT_APP_ID: ${{ secrets.BOT_APP_ID }}
      BOT_APP_PRIVATE_KEY: ${{ secrets.BOT_APP_PRIVATE_KEY }}
