---
name: "Test"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.head_ref }}-test
  cancel-in-progress: true

jobs:
  get-changed-images:
    uses: tuxpeople/containers/.github/workflows/get-changed-images.yaml@main

  list-build-images:
    needs: [get-changed-images]
    runs-on: ubuntu-latest
    name: list-build-images
    if: ${{ needs.get-changed-images.outputs.addedOrModified == 'true' }}
    steps:
      - run: |
          for file in ${{ needs.get-changed-images.outputs.addedOrModifiedImages }}; do
            echo "$file was changed"
          done

  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          dir_names: "true"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
